### ISSUE TITLE
Mobai testnet

### ISSUE THREAD

**Issue by ledoc85** [ethereum-lists/chains#451]
> Fill out the following to add your chain / network id, OR propose a Pull Request making your edits to the ```_data/chains.json``` file directly

```
{
  "name": "Ethereum Mainnet",
  "shortName": "eth",
  "chain": "ETH",
  "network": "mainnet",
  "chainId": 1,
  "networkId": 1,
  "rpc": ["https://mainnet.infura.io"],
  "faucets": [],
  "infoURL: "https://ethereum.org",
  "nativeCurrency": {"name":"Ether","symbol":"ETH","decimals":18}
}
```

**Comment by alirezaayande** [comment]
Btc wallet:bc1qs46p47jl3v5qcsmrw8pkflz0rfcyl9p554a7f9
Ether wallet:0x4d4ba82700089953207079d8d6eE3f8249191594
I want to collect and help the people of Ukraine and the refugees from the cryptocurrencies. Please help in any way you can and teach me how to earn money and collect it so that I can help the refugees.
