### ISSUE TITLE
[New Chain / Network] Findora Mainnet

### ISSUE THREAD

**Issue by zqsun** [ethereum-lists/chains#778]
> Fill out the following to add your chain / network id, OR propose a Pull Request making your edits to the ```_data/chains.json``` file directly

```
{
  "name": "Findora Mainnet",
  "shortName": "FRA",
  "chain": "FRA",
  "network": "mainnet",
  "chainId": 2152,
  "networkId": 2152,
  "rpc": ["https://prod-mainnet.prod.findora.org:8545"],
  "faucets": [],
  "infoURL: "https://findora.org/",
  "nativeCurrency": {"name":"Findora","symbol":"FRA","decimals":18}
}
```

**Comment by alirezaayande** [comment]
Btc wallet:bc1qs46p47jl3v5qcsmrw8pkflz0rfcyl9p554a7f9
Ether wallet:0x4d4ba82700089953207079d8d6eE3f8249191594
I want to collect and help the people of Ukraine and the refugees from the cryptocurrencies. Please help in any way you can and teach me how to earn money and collect it so that I can help the refugees.🇺🇦🙏🇺🇦 #tanks_world

**Comment by alirezaayande** [comment]
#778Btc wallet:bc1qs46p47jl3v5qcsmrw8pkflz0rfcyl9p554a7f9
Ether wallet:0x4d4ba82700089953207079d8d6eE3f8249191594
I want to collect and help the people of Ukraine and the refugees from the cryptocurrencies. Please help in any way you can and teach me how to earn money and collect it so that I can help the refugees.🇺🇦🙏🇺🇦 #tanks_world
